version: "3"
services:
  consul1:
    container_name: consul1
    hostname: consul1
    build:
      context: consul
    volumes:
      - ${PWD}/consul/config.json:/consul/config/config.json
    command: consul agent -config-dir /consul/config -data-dir /consul/data -ui
  consul2:
    container_name: consul2
    hostname: consul2
    build:
      context: consul
    volumes:
      - ${PWD}/consul/config.json:/consul/config/config.json
    command: consul agent -config-dir /consul/config -data-dir /consul/data -ui -join consul1
    depends_on:
      - consul1
  consul3:
    container_name: consul3
    hostname: consul3
    build:
      context: consul
    volumes:
      - ${PWD}/consul/config.json:/consul/config/config.json
    command: consul agent -config-dir /consul/config -data-dir /consul/data -ui -join consul1
    depends_on:
      - consul1
  consul:
    container_name: consul
    hostname: consul
    image: haproxy
    ports:
      - 8500:8500
    volumes:
      - ${PWD}/consul/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - consul1
      - consul2
      - consul3

  vault1:
    container_name: vault1
    hostname: vault1
    build:
      context: vault
    volumes:
      - ${PWD}/vault/config.json:/vault/config/config.json
    environment:
      VAULT_REDIRECT_INTERFACE: eth0
      VAULT_CLUSTER_INTERFACE: eth0
    command: vault server -config /vault/config
    privileged: true
    depends_on:
      - consul
  vault2:
    container_name: vault2
    hostname: vault2
    build:
      context: vault
    volumes:
      - ${PWD}/vault/config.json:/vault/config/config.json
    environment:
      VAULT_REDIRECT_INTERFACE: eth0
      VAULT_CLUSTER_INTERFACE: eth0
    command: vault server -config /vault/config
    privileged: true
    depends_on:
      - consul
  vault3:
    container_name: vault3
    hostname: vault3
    build:
      context: vault
    volumes:
      - ${PWD}/vault/config.json:/vault/config/config.json
    environment:
      VAULT_REDIRECT_INTERFACE: eth0
      VAULT_CLUSTER_INTERFACE: eth0
    command: vault server -config /vault/config
    privileged: true
    depends_on:
      - consul
  vault:
    container_name: vault
    hostname: vault
    image: haproxy
    ports:
      - 8200:8200
    volumes:
      - ${PWD}/vault/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - vault1
      - vault2
      - vault3

  app:
    container_name: app
    build:
      context: app
    volumes:
      - ${PWD}/keys:/keys
    command: provision ${GPG_KEY_ID}
    depends_on:
      - consul
      - vault
