version: "3"
services:
  consul1:
    container_name: consul1
    hostname: consul1
    build:
      context: consul
    command: agent -server
    ports:
      - 8500:8500
  consul2:
    container_name: consul2
    hostname: consul2
    build:
      context: consul
    command: agent -server -join consul1
    ports:
      - 8501:8500
    depends_on:
      - consul1
  consul3:
    container_name: consul3
    hostname: consul3
    build:
      context: consul
    command: agent -server -join consul1
    ports:
      - 8502:8500
    depends_on:
      - consul1
  vault1:
    container_name: vault1
    hostname: vault1
    build:
      context: vault
    command: server
    ports:
      - 8200:8200
    privileged: true
    depends_on:
      - consul1
      - consul2
      - consul3
  vault2:
    container_name: vault2
    hostname: vault2
    build:
      context: vault
    command: server
    ports:
      - 8201:8200
    privileged: true
    depends_on:
      - consul1
      - consul2
      - consul3
  vault3:
    container_name: vault3
    hostname: vault3
    build:
      context: vault
    command: server
    ports:
      - 8202:8200
    privileged: true
    depends_on:
      - consul1
      - consul2
      - consul3
  app:
    container_name: app
    build:
      context: app
    volumes:
      - ${PWD}/keys:/keys
    command: provision ${GPG_KEY_ID}
    depends_on:
      - consul1
      - consul2
      - consul3
      - vault1
      - vault2
      - vault3
